### ISSUE TITLE
Bug: Filename contains illegal characters

### ISSUE THREAD

**Issue by Lotus49b** [inhumantsar/slurp-extension#2]
Seems like some pages are generating illegal filenames.

Example: Are SAP users embracing AI?
source URL = https://erp.today/are-sap-users-embracing-ai/?utm_medium=email&_hsmi=302035235&utm_content=302035235&utm_source=hs_email

From Obsidian console log:
**************
app.js:1 Uncaught (in promise) Error: File name cannot contain any of the following characters: * " \ / < > : | ?
    at mb (app.js:1:718134)
    at t.checkPath (app.js:1:725357)
    at t.<anonymous> (app.js:1:727242)
    at app.js:1:237544
    at Object.next (app.js:1:237649)
    at app.js:1:236565
    at new Promise (<anonymous>)
    at v (app.js:1:236310)
    at t.create (app.js:1:727130)
    at SlurpPlugin.slurpNewNoteCallback (plugin:slurp:12125:42)
*****************

**Comment by inhumantsar** [comment]
thanks for this! should be a quick fix, keep your eyes peeled for an update sometime today

**Comment by inhumantsar** [comment]
this should be fixed now in [v0.1.6](https://github.com/inhumantsar/slurp/releases/tag/0.1.6)
